name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run:  curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
    - name: ls
      run: ls -l  
    - name: ls bin
      run: ls -l bin/
    - name: makesketch
      run: ./bin/arduino-cli sketch new MyFirstSketch
    - name: install esp8266
      run: ./bin/arduino-cli core install esp8266:esp8266 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json  
    - name: install python3
      run: sudo apt-get install -yq python3
    - name: compile
      run: ./bin/arduino-cli compile --fqbn esp8266:esp8266:d1 MyFirstSketch
    - uses: actions/upload-artifact@v1
      with:
        name: esp8266-d1-mini-4m.bin
        path: MyFirstSketch/MyFirstSketch.esp8266.esp8266.d1.bin 
